export const routes = {
    index: '',
    filterWallpapers: 'wallpapers',
    filterTexturesAndPatterns: 'textures-patterns',
    filterNature: 'nature',
    filterCurrentEvents: 'current-events',
    filterArchitecture: 'architecture',
    filterBusinessAndWork: 'business-work',
    filterAnimals: 'animals',
    filterTravel: 'travel',
    filterFashion: 'fashion',
    filterFoodAndDrink: 'food-drink',
    filterSpirituality: 'spirituality',
    filterExperimental: 'experimental',
    filterPeople: 'people',
    filterHealth: 'health',
    filterArtsAndCulture: 'arts-culture',
    notFound: '404',
};
